spring.application.name=grading

spring.datasource.url=jdbc:mysql://localhost:3306/grading_db
spring.datasource.username=root
spring.datasource.password=123456789

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8084

# عنوان السيرفر
spring.kafka.bootstrap-servers=localhost:9092

# إعدادات الـ Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# إعدادات الـ Consumer
spring.kafka.consumer.group-id=grading-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# المابينج عشان ميبوظش زي المرة اللي فاتت
spring.kafka.consumer.properties.spring.json.type.mapping=com.academicservice.demo.DTOS.events.EnrollmentEvent:com.grading.demo.dto.events.EnrollmentEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=*